import { environment } from '../../environments/environment';

export const ApiUrls = {
  baseUrl: environment.baseUrl,
  endpoints: {
    admin_login: 'admin/login',
    admin_refreshtoken: 'AdminApi/refreshtoken',
    admin_logout: 'UserApi/logout',
    admin_changepassword: 'admin/updatepassword',
    item_get: 'item/getitem',
    item_export: 'item/exportitem',
    item_getsummary: 'item/getitemsummary',
    item_process: 'item/itemprocess',
    item_getpricelog: 'item/getitempricelog',
    item_getpurchasing: 'item/getitempurchasing',
    item_getpurchasedlist: 'item/getpurchaseitemlist',
    item_purchasingprocess: 'item/itempurchasingprocess',
    item_purchasingpaymentprocess: 'item/itempurchasingpaymentprocess',
    item_getpurchasingpayment: 'item/getitempurchasingpayment',
    item_getusage: 'item/getitemusage',
    item_usageprocess: 'item/itemusageprocess',
    item_getinventory: 'item/getiteminventory',
    item_gettopselling: 'item/gettopsellingitem',
    invoice_monthlysales: 'invoice/monthlysales',
    invoice_clientdata: 'invoice/getinvoiceclientdata',
    invoice_topsellingitem: 'invoice/gettopsellingitem',
    invoice_salesreport: 'invoice/getsalesreport',
    invoice_get: 'invoice/getinvoice',
    invoice_export: 'invoice/exportinvoice',
    invoice_process: 'invoice/processinvoice',
    invoice_copy: 'invoice/invoicecopyrequest',
    invoice_copyaccesscheck: 'invoice/invoicecopyaccesscheck',
    invoice_copyconfirm: 'invoice/invociecopyconfirm',
    invoice_getinvoicedetail: 'invoice/getinvoicedetail',
    invoicedetail_process: 'invoice/processinvoicedetail',
    client_getpaymentdetail: 'client/getclientpayment',
    client_get: 'client/getclient',
    client_getreport: 'client/getclientreport',
    client_process: 'client/clientprocess',
    client_gettreatmentcheckin: 'client/gettreatmentcheckin',
    client_gettreatment: 'client/gettreatment',
    client_paymentprocess: 'client/processinvoicepayment',
    client_treatmentcheckinprocess: 'client/treatmentcheckinprocess',
    client_getdoctorinstruction: 'client/getdoctorinstruction',
    client_processdoctorinstruction: 'client/processdoctorinstruction',
    client_getdashboardinfo: 'client/getdashboardinfo',
    client_getbooking: 'client/getclientbooking',
    client_bookinprocess: 'client/clientbookingprocess',
    client_membercardprocess: 'client/clientmembercardprocess',
    client_getcurrentmembership: 'client/getclientcurrentmembership',
    client_getmembercard: 'client/getclientmembercard',
    client_getmembercardtransactions: 'client/getclientmembercardtransactions',
    doctorinstruction_getlast: 'doctorinstruction/getlastdoctorinstruction',
    holiday_get: 'holiday/getholidays',
    holiday_process: 'holiday/holidaysprocess',
    employee_get: 'employee/getemployee',
    employeeposition_get: 'employee/getemployeeposition',
    employeebank_get: 'employee/getemployeebank',
    employee_process: 'employee/employeeprocess',
    membercard_get: 'membercard/getmembercards',
    membershiptype_get: 'membership/getmembershiptype',
    membershiptypeitem_get: 'membership/getmembershiptypeitem',
    membershiptype_process: 'membership/membershiptypeprocess',
    membership_get: 'membership/getmembership',
    membership_process: 'membership/membershipprocess',
    membershiptransaction_get: 'membership/getmembershiptransaction',
    membershipclients_get: 'membership/getmembershipclients',
    membershipclients_process: 'membership/membershipclientprocess',
    membershipclients_getactivemembership:
      'membership/getclientactivemembership',
  },

  requestType: {
    GET: 'GET',
    POST: 'POST',
    PUT: 'PUT',
    DELETE: 'DELETE',
  },
};
